let R = require('ramda')

const data = [{"id":1,"market_cap":"$65.99M","sector":"Health Care","stock":"Midatech Pharma PLC","symbol":"MTP","industry":"Major Pharmaceuticals"},
{"id":2,"market_cap":"$4.82B","sector":"Consumer Non-Durables","stock":"Avnet, Inc.","symbol":"AVT","industry":"Electronic Components"},
{"id":3,"market_cap":"$84.27M","sector":"n/a","stock":"Blackrock Florida Municipal 2020 Term Trust","symbol":"BFO","industry":"n/a"},
{"id":4,"market_cap":"$463.59M","sector":"Health Care","stock":"Audentes Therapeutics, Inc.","symbol":"BOLD","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":5,"market_cap":"n/a","sector":"n/a","stock":"Colony NorthStar, Inc.","symbol":"CLNS^B","industry":"n/a"},
{"id":6,"market_cap":"$22.46M","sector":"Energy","stock":"Mesa Royalty Trust","symbol":"MTR","industry":"Oil & Gas Production"},
{"id":7,"market_cap":"$676.91M","sector":"Consumer Services","stock":"SP Plus Corporation","symbol":"SP","industry":"Rental/Leasing Companies"},
{"id":8,"market_cap":"$610.36M","sector":"Capital Goods","stock":"PGT Innovations, Inc.","symbol":"PGTI","industry":"Building Products"},
{"id":9,"market_cap":"$136.26M","sector":"n/a","stock":"Voya Natural Resources Equity Income Fund","symbol":"IRR","industry":"n/a"},
{"id":10,"market_cap":"$4.43B","sector":"Capital Goods","stock":"Bruker Corporation","symbol":"BRKR","industry":"Biotechnology: Laboratory Analytical Instruments"},
{"id":11,"market_cap":"$901.61M","sector":"n/a","stock":"John Hancock Tax Advantaged Dividend Income Fund","symbol":"HTD","industry":"n/a"},
{"id":12,"market_cap":"$40.78M","sector":"n/a","stock":"FlexShares Credit-Scored US Corporate Bond Index Fund","symbol":"SKOR","industry":"n/a"},
{"id":13,"market_cap":"$316.82M","sector":"Technology","stock":"SMART Global Holdings, Inc.","symbol":"SGH","industry":"Semiconductors"},
{"id":14,"market_cap":"$2.29B","sector":"Consumer Non-Durables","stock":"Steven Madden, Ltd.","symbol":"SHOO","industry":"Shoe Manufacturing"},
{"id":15,"market_cap":"$36.35M","sector":"Basic Industries","stock":"Female Health Company (The)","symbol":"FHCO","industry":"Specialty Chemicals"},
{"id":16,"market_cap":"$383.96M","sector":"n/a","stock":"PIMCO Municipal Income Fund III","symbol":"PMX","industry":"n/a"},
{"id":17,"market_cap":"$349.22M","sector":"Technology","stock":"Magic Software Enterprises Ltd.","symbol":"MGIC","industry":"Computer Software: Prepackaged Software"},
{"id":18,"market_cap":"$644.87M","sector":"Basic Industries","stock":"FutureFuel Corp.","symbol":"FF","industry":"Major Chemicals"},
{"id":19,"market_cap":"$1.77B","sector":"Miscellaneous","stock":"ExlService Holdings, Inc.","symbol":"EXLS","industry":"Business Services"},
{"id":20,"market_cap":"$7.87B","sector":"Consumer Services","stock":"Kimco Realty Corporation","symbol":"KIM","industry":"Real Estate Investment Trusts"},
{"id":21,"market_cap":"$206.36M","sector":"n/a","stock":"Ares Capital Corporation","symbol":"AFC","industry":"n/a"},
{"id":22,"market_cap":"$4.79M","sector":"Consumer Services","stock":"WPCS International Incorporated","symbol":"WPCS","industry":"Telecommunications Equipment"},
{"id":23,"market_cap":"$342.51M","sector":"Consumer Durables","stock":"Bassett Furniture Industries, Incorporated","symbol":"BSET","industry":"Home Furnishings"},
{"id":24,"market_cap":"$177M","sector":"Consumer Durables","stock":"Iridium Communications Inc","symbol":"IRDMB","industry":"Telecommunications Equipment"},
{"id":25,"market_cap":"$695.78M","sector":"Public Utilities","stock":"American Midstream Partners, LP","symbol":"AMID","industry":"Natural Gas Distribution"},
{"id":26,"market_cap":"$833.83M","sector":"Capital Goods","stock":"Modine Manufacturing Company","symbol":"MOD","industry":"Auto Parts:O.E.M."},
{"id":27,"market_cap":"n/a","sector":"n/a","stock":"Colony NorthStar, Inc.","symbol":"CLNS^D","industry":"n/a"},
{"id":28,"market_cap":"$41.88M","sector":"Consumer Services","stock":"CafePress Inc.","symbol":"PRSS","industry":"Other Specialty Stores"},
{"id":29,"market_cap":"$10.97B","sector":"Transportation","stock":"Alaska Air Group, Inc.","symbol":"ALK","industry":"Air Freight/Delivery Services"},
{"id":30,"market_cap":"$738.12M","sector":"Finance","stock":"Xenith Bankshares, Inc.","symbol":"XBKS","industry":"Major Banks"},
{"id":31,"market_cap":"$6.77B","sector":"Basic Industries","stock":"Chemours Company (The)","symbol":"CC","industry":"Major Chemicals"},
{"id":32,"market_cap":"$763.03M","sector":"Public Utilities","stock":"Archrock, Inc.","symbol":"AROC","industry":"Natural Gas Distribution"},
{"id":33,"market_cap":"n/a","sector":"Consumer Services","stock":"Gladstone Commercial Corporation","symbol":"GOODM","industry":"Real Estate"},
{"id":34,"market_cap":"$3.57B","sector":"Technology","stock":"MACOM Technology Solutions Holdings, Inc.","symbol":"MTSI","industry":"Semiconductors"},
{"id":35,"market_cap":"$63.73B","sector":"Energy","stock":"Enbridge Inc","symbol":"ENB","industry":"Natural Gas Distribution"},
{"id":36,"market_cap":"$123.38M","sector":"Health Care","stock":"Fate Therapeutics, Inc.","symbol":"FATE","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":37,"market_cap":"$7.68B","sector":"Consumer Services","stock":"Cencosud S.A.","symbol":"CNCO","industry":"Department/Specialty Retail Stores"},
{"id":38,"market_cap":"$506.02M","sector":"Capital Goods","stock":"Motorcar Parts of America, Inc.","symbol":"MPAA","industry":"Auto Parts:O.E.M."},
{"id":39,"market_cap":"$4.01B","sector":"Health Care","stock":"Galapagos NV","symbol":"GLPG","industry":"Major Pharmaceuticals"},
{"id":40,"market_cap":"$27.59M","sector":"Health Care","stock":"Threshold Pharmaceuticals, Inc.","symbol":"THLD","industry":"Major Pharmaceuticals"},
{"id":41,"market_cap":"$3.49B","sector":"Consumer Durables","stock":"Silgan Holdings Inc.","symbol":"SLGN","industry":"Containers/Packaging"},
{"id":42,"market_cap":"$34.26M","sector":"Health Care","stock":"BiondVax Pharmaceuticals Ltd.","symbol":"BVXV","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":43,"market_cap":"$499.2M","sector":"n/a","stock":"Calamos Global Dynamic Income Fund","symbol":"CHW","industry":"n/a"},
{"id":44,"market_cap":"$7.55B","sector":"Consumer Services","stock":"Kilroy Realty Corporation","symbol":"KRC","industry":"Real Estate Investment Trusts"},
{"id":45,"market_cap":"$219.23M","sector":"n/a","stock":"Fifth Street Senior Floating Rate Corp.","symbol":"FSFR","industry":"n/a"},
{"id":46,"market_cap":"$257.87M","sector":"Finance","stock":"The First Bancshares, Inc.","symbol":"FBMS","industry":"Major Banks"},
{"id":47,"market_cap":"$415.83M","sector":"n/a","stock":"Dreyfus Strategic Municipal Bond Fund, Inc.","symbol":"DSM","industry":"n/a"},
{"id":48,"market_cap":"$7.6B","sector":"Transportation","stock":"JetBlue Airways Corporation","symbol":"JBLU","industry":"Air Freight/Delivery Services"},
{"id":49,"market_cap":"$499.79M","sector":"Technology","stock":"Xactly Corporation","symbol":"XTLY","industry":"Computer Software: Prepackaged Software"},
{"id":50,"market_cap":"$637.42M","sector":"Energy","stock":"Global Partners LP","symbol":"GLP","industry":"Oil Refining/Marketing"},
{"id":51,"market_cap":"$3.43B","sector":"Consumer Non-Durables","stock":"Lancaster Colony Corporation","symbol":"LANC","industry":"Packaged Foods"},
{"id":52,"market_cap":"$973.21M","sector":"Finance","stock":"Marcus & Millichap, Inc.","symbol":"MMI","industry":"Real Estate"},
{"id":53,"market_cap":"$6.7B","sector":"Health Care","stock":"Herbalife LTD.","symbol":"HLF","industry":"Other Pharmaceuticals"},
{"id":54,"market_cap":"$6.89B","sector":"Health Care","stock":"Envision Healthcare Corporation","symbol":"EVHC","industry":"Medical/Nursing Services"},
{"id":55,"market_cap":"$1.41B","sector":"Finance","stock":"Yirendai Ltd.","symbol":"YRD","industry":"Finance: Consumer Services"},
{"id":56,"market_cap":"$1.37B","sector":"Finance","stock":"Employers Holdings Inc","symbol":"EIG","industry":"Property-Casualty Insurers"},
{"id":57,"market_cap":"$31.4M","sector":"Technology","stock":"Professional Diversity Network, Inc.","symbol":"IPDN","industry":"Computer Software: Programming, Data Processing"},
{"id":58,"market_cap":"$473.87M","sector":"Health Care","stock":"Capital Senior Living Corporation","symbol":"CSU","industry":"Hospital/Nursing Management"},
{"id":59,"market_cap":"$14.2M","sector":"Transportation","stock":"Euroseas Ltd.","symbol":"ESEA","industry":"Marine Transportation"},
{"id":60,"market_cap":"$51.49B","sector":"Consumer Services","stock":"Las Vegas Sands Corp.","symbol":"LVS","industry":"Hotels/Resorts"},
{"id":61,"market_cap":"$445.1M","sector":"Health Care","stock":"MyoKardia, Inc.","symbol":"MYOK","industry":"Major Pharmaceuticals"},
{"id":62,"market_cap":"$558.54M","sector":"Consumer Services","stock":"Duluth Holdings Inc.","symbol":"DLTH","industry":"Clothing/Shoe/Accessory Stores"},
{"id":63,"market_cap":"$472.08M","sector":"Finance","stock":"CardConnect Corp.","symbol":"CCN","industry":"Business Services"},
{"id":64,"market_cap":"$1.65B","sector":"n/a","stock":"BlackRock Municipal Target Term Trust Inc. (The)","symbol":"BTT","industry":"n/a"},
{"id":65,"market_cap":"$206.26M","sector":"n/a","stock":"John Hancock Hedged Equity & Income Fund","symbol":"HEQ","industry":"n/a"},
{"id":66,"market_cap":"$882.65M","sector":"Consumer Services","stock":"ICF International, Inc.","symbol":"ICFI","industry":"Professional Services"},
{"id":67,"market_cap":"n/a","sector":"Consumer Services","stock":"Daseke, Inc.","symbol":"DSKEW","industry":"Transportation Services"},
{"id":68,"market_cap":"n/a","sector":"Public Utilities","stock":"Entergy Mississippi, Inc.","symbol":"EMP","industry":"Electric Utilities: Central"},
{"id":69,"market_cap":"$3.2B","sector":"Consumer Services","stock":"MFA Financial, Inc.","symbol":"MFA","industry":"Real Estate Investment Trusts"},
{"id":70,"market_cap":"$4.86B","sector":"Capital Goods","stock":"MSC Industrial Direct Company, Inc.","symbol":"MSM","industry":"Industrial Machinery/Components"},
{"id":71,"market_cap":"n/a","sector":"n/a","stock":"Gabelli Dividend","symbol":"GDV^A","industry":"n/a"},
{"id":72,"market_cap":"n/a","sector":"n/a","stock":"CoreSite Realty Corporation","symbol":"COR^A","industry":"n/a"},
{"id":73,"market_cap":"n/a","sector":"n/a","stock":"Goldman Sachs Group, Inc. (The)","symbol":"GS^K","industry":"n/a"},
{"id":74,"market_cap":"$157.8M","sector":"Miscellaneous","stock":"Pendrell Corporation","symbol":"PCO","industry":"Multi-Sector Companies"},
{"id":75,"market_cap":"$13.11B","sector":"Finance","stock":"Comerica Incorporated","symbol":"CMA","industry":"Major Banks"},
{"id":76,"market_cap":"$445.1M","sector":"Health Care","stock":"MyoKardia, Inc.","symbol":"MYOK","industry":"Major Pharmaceuticals"},
{"id":77,"market_cap":"$30.92M","sector":"Health Care","stock":"Tonix Pharmaceuticals Holding Corp.","symbol":"TNXP","industry":"Major Pharmaceuticals"},
{"id":78,"market_cap":"$2.62B","sector":"Technology","stock":"Amaya Inc.","symbol":"AYA","industry":"Computer Software: Programming, Data Processing"},
{"id":79,"market_cap":"$382.11M","sector":"Technology","stock":"NeoPhotonics Corporation","symbol":"NPTN","industry":"Semiconductors"},
{"id":80,"market_cap":"$689.02M","sector":"Capital Goods","stock":"Douglas Dynamics, Inc.","symbol":"PLOW","industry":"Construction/Ag Equipment/Trucks"},
{"id":81,"market_cap":"$2.95B","sector":"Finance","stock":"Evercore Partners Inc","symbol":"EVR","industry":"Investment Managers"},
{"id":82,"market_cap":"n/a","sector":"Finance","stock":"Select Asset Inc.","symbol":"JBN","industry":"Finance: Consumer Services"},
{"id":83,"market_cap":"$1.76B","sector":"Health Care","stock":"Merit Medical Systems, Inc.","symbol":"MMSI","industry":"Medical/Dental Instruments"},
{"id":84,"market_cap":"$21.19B","sector":"Technology","stock":"DXC Technology Company","symbol":"DXC","industry":"EDP Services"},
{"id":85,"market_cap":"$592.24M","sector":"Health Care","stock":"Depomed, Inc.","symbol":"DEPO","industry":"Major Pharmaceuticals"},
{"id":86,"market_cap":"$631.55M","sector":"Consumer Services","stock":"Boingo Wireless, Inc.","symbol":"WIFI","industry":"Telecommunications Equipment"},
{"id":87,"market_cap":"$1.74B","sector":"Energy","stock":"SM Energy Company","symbol":"SM","industry":"Oil & Gas Production"},
{"id":88,"market_cap":"$225.47M","sector":"Finance","stock":"Codorus Valley Bancorp, Inc","symbol":"CVLY","industry":"Savings Institutions"},
{"id":89,"market_cap":"n/a","sector":"n/a","stock":"Federal Agricultural Mortgage Corporation","symbol":"AGM^B","industry":"n/a"},
{"id":90,"market_cap":"$204.76M","sector":"Health Care","stock":"Cempra, Inc.","symbol":"CEMP","industry":"Major Pharmaceuticals"},
{"id":91,"market_cap":"$1.33B","sector":"Technology","stock":"Tennant Company","symbol":"TNC","industry":"Industrial Machinery/Components"},
{"id":92,"market_cap":"$3.87B","sector":"Health Care","stock":"Neurocrine Biosciences, Inc.","symbol":"NBIX","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":93,"market_cap":"n/a","sector":"Finance","stock":"Legg Mason, Inc.","symbol":"LMHB","industry":"Investment Managers"},
{"id":94,"market_cap":"n/a","sector":"Public Utilities","stock":"Qwest Corporation","symbol":"CTY","industry":"Telecommunications Equipment"},
{"id":95,"market_cap":"$2.36B","sector":"Energy","stock":"MGE Energy Inc.","symbol":"MGEE","industry":"Electric Utilities: Central"},
{"id":96,"market_cap":"$1.83B","sector":"Basic Industries","stock":"Universal Forest Products, Inc.","symbol":"UFPI","industry":"Forest Products"},
{"id":97,"market_cap":"n/a","sector":"n/a","stock":"RAIT Financial Trust","symbol":"RAS^B","industry":"n/a"},
{"id":98,"market_cap":"$23.91B","sector":"Technology","stock":"Lam Research Corporation","symbol":"LRCX","industry":"Industrial Machinery/Components"},
{"id":99,"market_cap":"$54.18B","sector":"Consumer Services","stock":"JD.com, Inc.","symbol":"JD","industry":"Other Specialty Stores"},
{"id":100,"market_cap":"$1.2B","sector":"Health Care","stock":"LHC Group","symbol":"LHCG","industry":"Medical/Nursing Services"},
{"id":101,"market_cap":"$1.59B","sector":"Capital Goods","stock":"Orbotech Ltd.","symbol":"ORBK","industry":"Industrial Machinery/Components"},
{"id":102,"market_cap":"$213.38M","sector":"n/a","stock":"Morgan Stanley Emerging Markets Debt Fund, Inc.","symbol":"MSD","industry":"n/a"},
{"id":103,"market_cap":"$11.22B","sector":"Basic Industries","stock":"Goldcorp Inc.","symbol":"GG","industry":"Precious Metals"},
{"id":104,"market_cap":"n/a","sector":"Finance","stock":"Aegon NV","symbol":"AEK","industry":"Life Insurance"},
{"id":105,"market_cap":"$70.91B","sector":"Finance","stock":"Bank of Nova Scotia (The)","symbol":"BNS","industry":"Major Banks"},
{"id":106,"market_cap":"n/a","sector":"n/a","stock":"Ares Capital Corporation","symbol":"ARU.CL","industry":"n/a"},
{"id":107,"market_cap":"$243.18M","sector":"Health Care","stock":"Advaxis, Inc.","symbol":"ADXS","industry":"Major Pharmaceuticals"},
{"id":108,"market_cap":"$4.19B","sector":"Consumer Durables","stock":"Bemis Company, Inc.","symbol":"BMS","industry":"Containers/Packaging"},
{"id":109,"market_cap":"$10.29B","sector":"Finance","stock":"Woori Bank","symbol":"WF","industry":"Commercial Banks"},
{"id":110,"market_cap":"$153.95M","sector":"Consumer Durables","stock":"ChromaDex Corporation","symbol":"CDXC","industry":"Specialty Chemicals"},
{"id":111,"market_cap":"$607.83M","sector":"Finance","stock":"Greenhill & Co., Inc.","symbol":"GHL","industry":"Investment Bankers/Brokers/Service"},
{"id":112,"market_cap":"$1.57B","sector":"Consumer Services","stock":"Kite Realty Group Trust","symbol":"KRG","industry":"Real Estate Investment Trusts"},
{"id":113,"market_cap":"$28.79M","sector":"Health Care","stock":"CAS Medical Systems, Inc.","symbol":"CASM","industry":"Medical/Dental Instruments"},
{"id":114,"market_cap":"$22.92M","sector":"Technology","stock":"Top Image Systems, Ltd.","symbol":"TISA","industry":"Computer peripheral equipment"},
{"id":115,"market_cap":"n/a","sector":"n/a","stock":"PNC Financial Services Group, Inc. (The)","symbol":"PNC^P","industry":"n/a"},
{"id":116,"market_cap":"$4.35B","sector":"Consumer Non-Durables","stock":"Skechers U.S.A., Inc.","symbol":"SKX","industry":"Shoe Manufacturing"},
{"id":117,"market_cap":"$4.88B","sector":"Consumer Non-Durables","stock":"Compania Cervecerias Unidas, S.A.","symbol":"CCU","industry":"Beverages (Production/Distribution)"},
{"id":118,"market_cap":"$715.46M","sector":"Consumer Services","stock":"Sears Holdings Corporation","symbol":"SHLD","industry":"Department/Specialty Retail Stores"},
{"id":119,"market_cap":"$2.05B","sector":"Finance","stock":"Alexander & Baldwin Holdings, Inc.","symbol":"ALEX","industry":"Real Estate"},
{"id":120,"market_cap":"$608.57M","sector":"Energy","stock":"Thermon Group Holdings, Inc.","symbol":"THR","industry":"Industrial Machinery/Components"},
{"id":121,"market_cap":"$776.78M","sector":"Capital Goods","stock":"National Presto Industries, Inc.","symbol":"NPK","industry":"Ordnance And Accessories"},
{"id":122,"market_cap":"$4.14B","sector":"Finance","stock":"MGIC Investment Corporation","symbol":"MTG","industry":"Property-Casualty Insurers"},
{"id":123,"market_cap":"$112.52M","sector":"Finance","stock":"JMP Group LLC","symbol":"JMP","industry":"Investment Bankers/Brokers/Service"},
{"id":124,"market_cap":"$679.83M","sector":"n/a","stock":"H&E Equipment Services, Inc.","symbol":"HEES","industry":"n/a"},
{"id":125,"market_cap":"$4.63M","sector":"n/a","stock":"First Trust China AlphaDEX Fund","symbol":"FCA","industry":"n/a"},
{"id":126,"market_cap":"$8.63B","sector":"Public Utilities","stock":"Targa Resources, Inc.","symbol":"TRGP","industry":"Natural Gas Distribution"},
{"id":127,"market_cap":"$538.84M","sector":"n/a","stock":"Adams Natural Resources Fund, Inc.","symbol":"PEO","industry":"n/a"},
{"id":128,"market_cap":"$1.25B","sector":"Capital Goods","stock":"Altra Industrial Motion Corp.","symbol":"AIMC","industry":"Industrial Machinery/Components"},
{"id":129,"market_cap":"n/a","sector":"Consumer Durables","stock":"Nexeo Solutions, Inc.","symbol":"NXEOU","industry":"Specialty Chemicals"},
{"id":130,"market_cap":"$21.14B","sector":"Capital Goods","stock":"Rockwell Automation, Inc.","symbol":"ROK","industry":"Industrial Machinery/Components"},
{"id":131,"market_cap":"$5.1B","sector":"Basic Industries","stock":"Kinross Gold Corporation","symbol":"KGC","industry":"Precious Metals"},
{"id":132,"market_cap":"$62M","sector":"Health Care","stock":"Diversicare Healthcare Services Inc.","symbol":"DVCR","industry":"Hospital/Nursing Management"},
{"id":133,"market_cap":"$4.14B","sector":"Finance","stock":"Realogy Holdings Corp.","symbol":"RLGY","industry":"Real Estate"},
{"id":134,"market_cap":"$14.73B","sector":"Health Care","stock":"Quest Diagnostics Incorporated","symbol":"DGX","industry":"Medical Specialities"},
{"id":135,"market_cap":"$568.21M","sector":"n/a","stock":"Nuveen High Income November 2021 Target Term Fund","symbol":"JHB","industry":"n/a"},
{"id":136,"market_cap":"$1.28B","sector":"Basic Industries","stock":"Osisko Gold Royalties Ltd","symbol":"OR","industry":"Precious Metals"},
{"id":137,"market_cap":"$743.72M","sector":"n/a","stock":"Nuveen California AMT-Free Quality Municipal Income Fund","symbol":"NKX","industry":"n/a"},
{"id":138,"market_cap":"$1.35B","sector":"Health Care","stock":"Amicus Therapeutics, Inc.","symbol":"FOLD","industry":"Major Pharmaceuticals"},
{"id":139,"market_cap":"$4.09B","sector":"Finance","stock":"First Horizon National Corporation","symbol":"FHN","industry":"Major Banks"},
{"id":140,"market_cap":"$3.27B","sector":"Finance","stock":"Pinnacle Financial Partners, Inc.","symbol":"PNFP","industry":"Major Banks"},
{"id":141,"market_cap":"$2.93B","sector":"Capital Goods","stock":"Visteon Corporation","symbol":"VC","industry":"Auto Parts:O.E.M."},
{"id":142,"market_cap":"$5.64B","sector":"Public Utilities","stock":"EQT Midstream Partners, LP","symbol":"EQM","industry":"Natural Gas Distribution"},
{"id":143,"market_cap":"$523.31M","sector":"Consumer Services","stock":"Winmark Corporation","symbol":"WINA","industry":"Other Specialty Stores"},
{"id":144,"market_cap":"$2.31M","sector":"Health Care","stock":"Anthera Pharmaceuticals, Inc.","symbol":"ANTH","industry":"Major Pharmaceuticals"},
{"id":145,"market_cap":"$2.88B","sector":"Capital Goods","stock":"Taylor Morrison Home Corporation","symbol":"TMHC","industry":"Homebuilding"},
{"id":146,"market_cap":"$328.51M","sector":"n/a","stock":"Nuveen Real Estate Fund","symbol":"JRS","industry":"n/a"},
{"id":147,"market_cap":"n/a","sector":"Health Care","stock":"Medovex Corp.","symbol":"MDVXW","industry":"Medical/Dental Instruments"},
{"id":148,"market_cap":"$49.84B","sector":"Health Care","stock":"Shire plc","symbol":"SHPG","industry":"Major Pharmaceuticals"},
{"id":149,"market_cap":"$79.41B","sector":"Technology","stock":"Texas Instruments Incorporated","symbol":"TXN","industry":"Semiconductors"},
{"id":150,"market_cap":"n/a","sector":"Transportation","stock":"SEACOR Marine Holdings Inc.","symbol":"SMHI","industry":"Marine Transportation"},
{"id":151,"market_cap":"$2.49B","sector":"Transportation","stock":"Hawaiian Holdings, Inc.","symbol":"HA","industry":"Air Freight/Delivery Services"},
{"id":152,"market_cap":"$1.81B","sector":"n/a","stock":"Gabelli Dividend","symbol":"GDV","industry":"n/a"},
{"id":153,"market_cap":"$39.94M","sector":"Consumer Non-Durables","stock":"Ever-Glory International Group, Inc.","symbol":"EVK","industry":"Apparel"},
{"id":154,"market_cap":"$386.58M","sector":"n/a","stock":"Nuveen Global High Income Fund","symbol":"JGH","industry":"n/a"},
{"id":155,"market_cap":"$380.76M","sector":"Public Utilities","stock":"Clean Energy Fuels Corp.","symbol":"CLNE","industry":"Natural Gas Distribution"},
{"id":156,"market_cap":"$133.17M","sector":"n/a","stock":"THL Credit Senior Loan Fund","symbol":"TSLF","industry":"n/a"},
{"id":157,"market_cap":"$3.76B","sector":"Consumer Services","stock":"Spirit Realty Capital, Inc.","symbol":"SRC","industry":"Building operators"},
{"id":158,"market_cap":"$434.22M","sector":"n/a","stock":"Nuveen New York Quality Municipal Income Fund","symbol":"NAN","industry":"n/a"},
{"id":159,"market_cap":"n/a","sector":"Consumer Services","stock":"Public Storage","symbol":"PSA^E","industry":"Real Estate Investment Trusts"},
{"id":160,"market_cap":"n/a","sector":"n/a","stock":"Assured Guaranty Ltd.","symbol":"AGO^F","industry":"n/a"},
{"id":161,"market_cap":"$169.43M","sector":"Finance","stock":"Blue Capital Reinsurance Holdings Ltd.","symbol":"BCRH","industry":"Property-Casualty Insurers"},
{"id":162,"market_cap":"$65.99M","sector":"Health Care","stock":"Midatech Pharma PLC","symbol":"MTP","industry":"Major Pharmaceuticals"},
{"id":163,"market_cap":"n/a","sector":"n/a","stock":"Prudential Public Limited Company","symbol":"PUK^A","industry":"n/a"},
{"id":164,"market_cap":"$195.66M","sector":"Finance","stock":"Penns Woods Bancorp, Inc.","symbol":"PWOD","industry":"Major Banks"},
{"id":165,"market_cap":"$299.6M","sector":"n/a","stock":"First Trust","symbol":"FFA","industry":"n/a"},
{"id":166,"market_cap":"$1.18B","sector":"n/a","stock":"Vanguard Russell 1000 Growth ETF","symbol":"VONG","industry":"n/a"},
{"id":167,"market_cap":"n/a","sector":"Public Utilities","stock":"Telephone and Data Systems, Inc.","symbol":"TDI","industry":"Telecommunications Equipment"},
{"id":168,"market_cap":"$4.01B","sector":"Technology","stock":"Monolithic Power Systems, Inc.","symbol":"MPWR","industry":"Semiconductors"},
{"id":169,"market_cap":"$89.69M","sector":"Energy","stock":"Sevcon, Inc.","symbol":"SEV","industry":"Industrial Machinery/Components"},
{"id":170,"market_cap":"n/a","sector":"n/a","stock":"M/I Homes, Inc.","symbol":"MHO^A","industry":"n/a"},
{"id":171,"market_cap":"n/a","sector":"n/a","stock":"PS Business Parks, Inc.","symbol":"PSB^V","industry":"n/a"},
{"id":172,"market_cap":"n/a","sector":"Miscellaneous","stock":"B. Riley Financial, Inc.","symbol":"RILYL","industry":"Business Services"},
{"id":173,"market_cap":"$641.08M","sector":"Capital Goods","stock":"Nova Measuring Instruments Ltd.","symbol":"NVMI","industry":"Electronic Components"},
{"id":174,"market_cap":"$27.17B","sector":"Miscellaneous","stock":"Ctrip.com International, Ltd.","symbol":"CTRP","industry":"Business Services"},
{"id":175,"market_cap":"$26.61M","sector":"Public Utilities","stock":"Otelco Inc.","symbol":"OTEL","industry":"Telecommunications Equipment"},
{"id":176,"market_cap":"n/a","sector":"n/a","stock":"Citigroup Inc.","symbol":"C^P","industry":"n/a"},
{"id":177,"market_cap":"$61.78M","sector":"Capital Goods","stock":"ARC Group Worldwide, Inc.","symbol":"ARCW","industry":"Metal Fabrications"},
{"id":178,"market_cap":"$33.43M","sector":"Consumer Durables","stock":"Jason Industries, Inc.","symbol":"JASN","industry":"Miscellaneous manufacturing industries"},
{"id":179,"market_cap":"$8.02B","sector":"Basic Industries","stock":"Steel Dynamics, Inc.","symbol":"STLD","industry":"Steel/Iron Ore"},
{"id":180,"market_cap":"n/a","sector":"Health Care","stock":"Cellectar Biosciences, Inc.","symbol":"CLRBZ","industry":"Major Pharmaceuticals"},
{"id":181,"market_cap":"$35.47M","sector":"Health Care","stock":"Histogenics Corporation","symbol":"HSGX","industry":"Industrial Specialties"},
{"id":182,"market_cap":"$48.52M","sector":"Consumer Services","stock":"The ONE Group Hospitality, Inc.","symbol":"STKS","industry":"Restaurants"},
{"id":183,"market_cap":"n/a","sector":"Consumer Durables","stock":"GP Investments Acquisition Corp.","symbol":"GPIAU","industry":"Home Furnishings"},
{"id":184,"market_cap":"$44.42M","sector":"Health Care","stock":"Tandem Diabetes Care, Inc.","symbol":"TNDM","industry":"Medical/Dental Instruments"},
{"id":185,"market_cap":"$46.84M","sector":"Finance","stock":"Melrose Bancorp, Inc.","symbol":"MELR","industry":"Major Banks"},
{"id":186,"market_cap":"$22.51M","sector":"n/a","stock":"PowerShares LadderRite 0-5 Year Corporate Bond Portfolio","symbol":"LDRI","industry":"n/a"},
{"id":187,"market_cap":"$181.01M","sector":"n/a","stock":"Delaware Enhanced Global Dividend","symbol":"DEX","industry":"n/a"},
{"id":188,"market_cap":"$2.89B","sector":"Public Utilities","stock":"South Jersey Industries, Inc.","symbol":"SJI","industry":"Oil/Gas Transmission"},
{"id":189,"market_cap":"$272.97M","sector":"Health Care","stock":"Organovo Holdings, Inc.","symbol":"ONVO","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":190,"market_cap":"$4.03B","sector":"Energy","stock":"Weatherford International plc","symbol":"WFT","industry":"Metal Fabrications"},
{"id":191,"market_cap":"$662.05M","sector":"Finance","stock":"Bridge Bancorp, Inc.","symbol":"BDGE","industry":"Major Banks"},
{"id":192,"market_cap":"$96.67B","sector":"Technology","stock":"NTT DOCOMO, Inc","symbol":"DCM","industry":"Radio And Television Broadcasting And Communications Equipment"},
{"id":193,"market_cap":"$26.78B","sector":"Public Utilities","stock":"Edison International","symbol":"EIX","industry":"Electric Utilities: Central"},
{"id":194,"market_cap":"$208.41M","sector":"n/a","stock":"The Gabelli Healthcare & Wellness Trust","symbol":"GRX","industry":"n/a"},
{"id":195,"market_cap":"$1.7B","sector":"Health Care","stock":"Pacira Pharmaceuticals, Inc.","symbol":"PCRX","industry":"Major Pharmaceuticals"},
{"id":196,"market_cap":"$126.72M","sector":"n/a","stock":"PIMCO Commercial Mortgage Securities Trust, Inc.","symbol":"PCM","industry":"n/a"},
{"id":197,"market_cap":"$2.76B","sector":"Energy","stock":"Jagged Peak Energy Inc.","symbol":"JAG","industry":"Oil & Gas Production"},
{"id":198,"market_cap":"$16.13M","sector":"Consumer Services","stock":"Wheeler Real Estate Investment Trust, Inc.","symbol":"WHLRP","industry":"Real Estate Investment Trusts"},
{"id":199,"market_cap":"$56.68M","sector":"Consumer Durables","stock":"Pioneer Power Solutions, Inc.","symbol":"PPSI","industry":"Electrical Products"},
{"id":200,"market_cap":"$54.29M","sector":"Health Care","stock":"Microbot Medical Inc. ","symbol":"MBOT","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":201,"market_cap":"$2.32B","sector":"Basic Industries","stock":"Yamana Gold Inc.","symbol":"AUY","industry":"Precious Metals"},
{"id":202,"market_cap":"$16.52B","sector":"Basic Industries","stock":"Freeport-McMoran, Inc.","symbol":"FCX","industry":"Precious Metals"},
{"id":203,"market_cap":"$97.38M","sector":"Finance","stock":"VelocityShares 3x Long Gold ETN","symbol":"UGLD","industry":"Investment Bankers/Brokers/Service"},
{"id":204,"market_cap":"$1.57B","sector":"Consumer Services","stock":"Kite Realty Group Trust","symbol":"KRG","industry":"Real Estate Investment Trusts"},
{"id":205,"market_cap":"$1.25B","sector":"Finance","stock":"Heartland Financial USA, Inc.","symbol":"HTLF","industry":"Major Banks"},
{"id":206,"market_cap":"$2.41B","sector":"Energy","stock":"Texas Pacific Land Trust","symbol":"TPL","industry":"Oil & Gas Production"},
{"id":207,"market_cap":"$37.26B","sector":"Public Utilities","stock":"Williams Partners LP","symbol":"WPZ","industry":"Natural Gas Distribution"},
{"id":208,"market_cap":"$1.41B","sector":"Public Utilities","stock":"Empresa Distribuidora Y Comercializadora Norte S.A. (Edenor)","symbol":"EDN","industry":"Electric Utilities: Central"},
{"id":209,"market_cap":"$689.02M","sector":"Capital Goods","stock":"Douglas Dynamics, Inc.","symbol":"PLOW","industry":"Construction/Ag Equipment/Trucks"},
{"id":210,"market_cap":"$3.72B","sector":"Public Utilities","stock":"NewJersey Resources Corporation","symbol":"NJR","industry":"Oil/Gas Transmission"},
{"id":211,"market_cap":"$296.89M","sector":"n/a","stock":"Voya Infrastructure, Industrials and Materials Fund","symbol":"IDE","industry":"n/a"},
{"id":212,"market_cap":"$4.54B","sector":"Technology","stock":"Gardner Denver Holdings, Inc.","symbol":"GDI","industry":"Industrial Machinery/Components"},
{"id":213,"market_cap":"$2.72B","sector":"Finance","stock":"TCF Financial Corporation","symbol":"TCF","industry":"Major Banks"},
{"id":214,"market_cap":"$1.4B","sector":"Technology","stock":"OSI Systems, Inc.","symbol":"OSIS","industry":"Semiconductors"},
{"id":215,"market_cap":"$782.71M","sector":"Consumer Services","stock":"Hertz Global Holdings, Inc","symbol":"HTZ","industry":"Rental/Leasing Companies"},
{"id":216,"market_cap":"$185.56M","sector":"Finance","stock":"Chemung Financial Corp","symbol":"CHMG","industry":"Major Banks"},
{"id":217,"market_cap":"n/a","sector":"n/a","stock":"Vornado Realty Trust","symbol":"VNO^I","industry":"n/a"},
{"id":218,"market_cap":"$182.87M","sector":"n/a","stock":"PowerShares DWA SmallCap Momentum Portfolio","symbol":"DWAS","industry":"n/a"},
{"id":219,"market_cap":"$16.97B","sector":"Consumer Services","stock":"Best Buy Co., Inc.","symbol":"BBY","industry":"Consumer Electronics/Video Chains"},
{"id":220,"market_cap":"$167.24M","sector":"Finance","stock":"ASB Bancorp, Inc.","symbol":"ASBB","industry":"Savings Institutions"},
{"id":221,"market_cap":"$3.87B","sector":"Capital Goods","stock":"EMCOR Group, Inc.","symbol":"EME","industry":"Engineering & Construction"},
{"id":222,"market_cap":"n/a","sector":"n/a","stock":"Seaspan Corporation","symbol":"SSW^E","industry":"n/a"},
{"id":223,"market_cap":"n/a","sector":"n/a","stock":"Cullen/Frost Bankers, Inc.","symbol":"CFR^A","industry":"n/a"},
{"id":224,"market_cap":"$41.88M","sector":"Consumer Services","stock":"CafePress Inc.","symbol":"PRSS","industry":"Other Specialty Stores"},
{"id":225,"market_cap":"$2.5B","sector":"Consumer Services","stock":"QTS Realty Trust, Inc.","symbol":"QTS","industry":"Real Estate Investment Trusts"},
{"id":226,"market_cap":"$13.2M","sector":"Energy","stock":"Ocean Rig UDW Inc.","symbol":"ORIG","industry":"Oil & Gas Production"},
{"id":227,"market_cap":"$35.52M","sector":"Finance","stock":"Atlanticus Holdings Corporation","symbol":"ATLC","industry":"Finance: Consumer Services"},
{"id":228,"market_cap":"$21.6M","sector":"Technology","stock":"BroadVision, Inc.","symbol":"BVSN","industry":"Computer Software: Prepackaged Software"},
{"id":229,"market_cap":"$92.34B","sector":"Basic Industries","stock":"BHP Billiton Limited","symbol":"BHP","industry":"Precious Metals"},
{"id":230,"market_cap":"$724.86M","sector":"Consumer Services","stock":"New Media Investment Group Inc.","symbol":"NEWM","industry":"Newspapers/Magazines"},
{"id":231,"market_cap":"$286.77M","sector":"Basic Industries","stock":"Sterling Construction Company Inc","symbol":"STRL","industry":"Military/Government/Technical"},
{"id":232,"market_cap":"$665.88M","sector":"Finance","stock":"The First of Long Island Corporation","symbol":"FLIC","industry":"Major Banks"},
{"id":233,"market_cap":"$266.19M","sector":"Technology","stock":"Kopin Corporation","symbol":"KOPN","industry":"Semiconductors"},
{"id":234,"market_cap":"$271.31M","sector":"n/a","stock":"Blackstone GSO Senior Floating Rate Term Fund","symbol":"BSL","industry":"n/a"},
{"id":235,"market_cap":"$1.26B","sector":"Capital Goods","stock":"Wabash National Corporation","symbol":"WNC","industry":"Construction/Ag Equipment/Trucks"},
{"id":236,"market_cap":"$4.45B","sector":"Finance","stock":"TFS Financial Corporation","symbol":"TFSL","industry":"Savings Institutions"},
{"id":237,"market_cap":"$1.72B","sector":"Finance","stock":"OneBeacon Insurance Group, Ltd.","symbol":"OB","industry":"Property-Casualty Insurers"},
{"id":238,"market_cap":"$58.47M","sector":"n/a","stock":"Blackrock Muni New York Intermediate Duration Fund Inc","symbol":"MNE","industry":"n/a"},
{"id":239,"market_cap":"$4.5B","sector":"Miscellaneous","stock":"WEX Inc.","symbol":"WEX","industry":"Business Services"},
{"id":240,"market_cap":"$92.4M","sector":"Energy","stock":"Cross Timbers Royalty Trust","symbol":"CRT","industry":"Oil & Gas Production"},
{"id":241,"market_cap":"$16.53M","sector":"n/a","stock":"WisdomTree Negative Duration High Yield Bond Fund","symbol":"HYND","industry":"n/a"},
{"id":242,"market_cap":"$1.53B","sector":"Finance","stock":"Union Bankshares Corporation","symbol":"UBSH","industry":"Major Banks"},
{"id":243,"market_cap":"$463.93M","sector":"n/a","stock":"AllianzGI Convertible & Income Fund II","symbol":"NCZ","industry":"n/a"},
{"id":244,"market_cap":"$2.18B","sector":"n/a","stock":"Nuveen California Quality Municipal Income Fund","symbol":"NAC","industry":"n/a"},
{"id":245,"market_cap":"$84.27M","sector":"Finance","stock":"Guaranty Federal Bancshares, Inc.","symbol":"GFED","industry":"Major Banks"},
{"id":246,"market_cap":"$3.76B","sector":"Consumer Services","stock":"Spirit Realty Capital, Inc.","symbol":"SRC","industry":"Building operators"},
{"id":247,"market_cap":"n/a","sector":"n/a","stock":"The Gabelli Healthcare & Wellness Trust","symbol":"GRX^A","industry":"n/a"},
{"id":248,"market_cap":"$3.5B","sector":"Health Care","stock":"Healthcare Services Group, Inc.","symbol":"HCSG","industry":"Hospital/Nursing Management"},
{"id":249,"market_cap":"$261.12M","sector":"Consumer Non-Durables","stock":"Alico, Inc.","symbol":"ALCO","industry":"Farming/Seeds/Milling"},
{"id":250,"market_cap":"$2.12B","sector":"Consumer Services","stock":"Bloomin&#39; Brands, Inc.","symbol":"BLMN","industry":"Restaurants"},
{"id":251,"market_cap":"$35.98B","sector":"Technology","stock":"Vmware, Inc.","symbol":"VMW","industry":"Computer Software: Prepackaged Software"},
{"id":252,"market_cap":"$9.71M","sector":"n/a","stock":"First Trust Indxx Global Natural Resources Income ETF","symbol":"FTRI","industry":"n/a"},
{"id":253,"market_cap":"n/a","sector":"Finance","stock":"Citigroup Inc.","symbol":"C^N","industry":"Major Banks"},
{"id":254,"market_cap":"$3.17B","sector":"Public Utilities","stock":"PNM Resources, Inc. (Holding Co.)","symbol":"PNM","industry":"Electric Utilities: Central"},
{"id":255,"market_cap":"$141.43M","sector":"Consumer Non-Durables","stock":"Amira Nature Foods Ltd","symbol":"ANFI","industry":"Packaged Foods"},
{"id":256,"market_cap":"$1.17B","sector":"n/a","stock":"Nuveen Credit Strategies Income Fund","symbol":"JQC","industry":"n/a"},
{"id":257,"market_cap":"$37M","sector":"Finance","stock":"National Security Group, Inc.","symbol":"NSEC","industry":"Life Insurance"},
{"id":258,"market_cap":"$191.02M","sector":"n/a","stock":"BlackRock New York Investment Quality Municipal Trust Inc. (Th","symbol":"BNY","industry":"n/a"},
{"id":259,"market_cap":"$774.83M","sector":"Energy","stock":"Energy XXI Gulf Coast, Inc.","symbol":"EXXI","industry":"Oil & Gas Production"},
{"id":260,"market_cap":"$34.48M","sector":"Health Care","stock":"Oncobiologics, Inc.","symbol":"ONS","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":261,"market_cap":"$36.87M","sector":"Consumer Durables","stock":"Mannatech, Incorporated","symbol":"MTEX","industry":"Specialty Chemicals"},
{"id":262,"market_cap":"$84.3M","sector":"Health Care","stock":"AVEO Pharmaceuticals, Inc.","symbol":"AVEO","industry":"Major Pharmaceuticals"},
{"id":263,"market_cap":"$3.65B","sector":"Energy","stock":"Genesis Energy, L.P.","symbol":"GEL","industry":"Oil Refining/Marketing"},
{"id":264,"market_cap":"$17.3B","sector":"Technology","stock":"Symantec Corporation","symbol":"SYMC","industry":"Computer Software: Prepackaged Software"},
{"id":265,"market_cap":"$40.91B","sector":"Capital Goods","stock":"Deere & Company","symbol":"DE","industry":"Industrial Machinery/Components"},
{"id":266,"market_cap":"n/a","sector":"n/a","stock":"Mota Group, Inc.","symbol":"MOTA","industry":"n/a"},
{"id":267,"market_cap":"$22.77M","sector":"Capital Goods","stock":"Uni-Pixel, Inc.","symbol":"UNXL","industry":"Industrial Machinery/Components"},
{"id":268,"market_cap":"$629.54M","sector":"Finance","stock":"QCR Holdings, Inc.","symbol":"QCRH","industry":"Major Banks"},
{"id":269,"market_cap":"n/a","sector":"n/a","stock":"Bank of America Corporation","symbol":"BAC^E","industry":"n/a"},
{"id":270,"market_cap":"n/a","sector":"n/a","stock":"Annaly Capital Management Inc","symbol":"NLY^D","industry":"n/a"},
{"id":271,"market_cap":"$70.35M","sector":"Consumer Services","stock":"J. W. Mays, Inc.","symbol":"MAYS","industry":"Building operators"},
{"id":272,"market_cap":"n/a","sector":"n/a","stock":"Dynegy Inc.","symbol":"DYN^A","industry":"n/a"},
{"id":273,"market_cap":"$4.43B","sector":"Capital Goods","stock":"Bruker Corporation","symbol":"BRKR","industry":"Biotechnology: Laboratory Analytical Instruments"},
{"id":274,"market_cap":"$11.67B","sector":"Health Care","stock":"Align Technology, Inc.","symbol":"ALGN","industry":"Industrial Specialties"},
{"id":275,"market_cap":"n/a","sector":"n/a","stock":"CBS Corporation","symbol":"CBS.A","industry":"n/a"},
{"id":276,"market_cap":"$197.05M","sector":"n/a","stock":"Voya Global Advantage and Premium Opportunity Fund","symbol":"IGA","industry":"n/a"},
{"id":277,"market_cap":"$195.98M","sector":"Consumer Non-Durables","stock":"New Age Beverages Corporation","symbol":"NBEV","industry":"Beverages (Production/Distribution)"},
{"id":278,"market_cap":"$577.43M","sector":"Health Care","stock":"Versartis, Inc.","symbol":"VSAR","industry":"Major Pharmaceuticals"},
{"id":279,"market_cap":"$806.93M","sector":"Public Utilities","stock":"Spark Energy, Inc.","symbol":"SPKE","industry":"Power Generation"},
{"id":280,"market_cap":"$25.39B","sector":"Health Care","stock":"Zimmer Biomet Holdings, Inc.","symbol":"ZBH","industry":"Industrial Specialties"},
{"id":281,"market_cap":"$42.87B","sector":"Finance","stock":"CME Group Inc.","symbol":"CME","industry":"Investment Bankers/Brokers/Service"},
{"id":282,"market_cap":"$5.07B","sector":"Technology","stock":"Siliconware Precision Industries Company, Ltd.","symbol":"SPIL","industry":"Semiconductors"},
{"id":283,"market_cap":"$27.34M","sector":"Finance","stock":"BancFirst Corporation","symbol":"BANFP","industry":"Major Banks"},
{"id":284,"market_cap":"$41.02M","sector":"Energy","stock":"Mid-Con Energy Partners, LP","symbol":"MCEP","industry":"Oil & Gas Production"},
{"id":285,"market_cap":"$5.97B","sector":"Consumer Services","stock":"Park Hotels & Resorts Inc.","symbol":"PK","industry":"Hotels/Resorts"},
{"id":286,"market_cap":"$48.81M","sector":"Technology","stock":"MIND C.T.I. Ltd.","symbol":"MNDO","industry":"EDP Services"},
{"id":287,"market_cap":"$58.46M","sector":"n/a","stock":"iShares MSCI Brazil Small-Cap ETF","symbol":"EWZS","industry":"n/a"},
{"id":288,"market_cap":"n/a","sector":"n/a","stock":"New York Community Bancorp, Inc.","symbol":"NYCB^A","industry":"n/a"},
{"id":289,"market_cap":"n/a","sector":"n/a","stock":"Sunstone Hotel Investors, Inc.","symbol":"SHO^F","industry":"n/a"},
{"id":290,"market_cap":"$5.45B","sector":"Finance","stock":"Jones Lang LaSalle Incorporated","symbol":"JLL","industry":"Real Estate"},
{"id":291,"market_cap":"$250.05M","sector":"n/a","stock":"Nuveen AMT-Free Municipal Value Fund","symbol":"NUW","industry":"n/a"},
{"id":292,"market_cap":"$20.2B","sector":"Health Care","stock":"AmerisourceBergen Corporation (Holding Co)","symbol":"ABC","industry":"Other Pharmaceuticals"},
{"id":293,"market_cap":"$1.69B","sector":"Technology","stock":"Celestica, Inc.","symbol":"CLS","industry":"Electrical Products"},
{"id":294,"market_cap":"$3.41B","sector":"Consumer Non-Durables","stock":"Entegris, Inc.","symbol":"ENTG","industry":"Plastic Products"},
{"id":295,"market_cap":"$8.17M","sector":"Health Care","stock":"Interpace Diagnostics Group, Inc.","symbol":"IDXG","industry":"Medical/Dental Instruments"},
{"id":296,"market_cap":"$51.13M","sector":"Consumer Services","stock":"Acorn International, Inc.","symbol":"ATV","industry":"Other Specialty Stores"},
{"id":297,"market_cap":"$2.5B","sector":"Basic Industries","stock":"Minerals Technologies Inc.","symbol":"MTX","industry":"Major Chemicals"},
{"id":298,"market_cap":"$1.77B","sector":"Basic Industries","stock":"Allegheny Technologies Incorporated","symbol":"ATI","industry":"Steel/Iron Ore"},
{"id":299,"market_cap":"$2.71B","sector":"Capital Goods","stock":"Dorman Products, Inc.","symbol":"DORM","industry":"Auto Parts:O.E.M."},
{"id":300,"market_cap":"$5.84B","sector":"Consumer Non-Durables","stock":"Pilgrim&#39;s Pride Corporation","symbol":"PPC","industry":"Meat/Poultry/Fish"},
{"id":301,"market_cap":"$178.04M","sector":"Capital Goods","stock":"Carbo Ceramics, Inc.","symbol":"CRR","industry":"Industrial Machinery/Components"},
{"id":302,"market_cap":"n/a","sector":"Consumer Services","stock":"GGP Inc.","symbol":"GGP^A","industry":"Real Estate Investment Trusts"},
{"id":303,"market_cap":"$24.52M","sector":"Health Care","stock":"Diffusion Pharmaceuticals Inc.","symbol":"DFFN","industry":"Major Pharmaceuticals"},
{"id":304,"market_cap":"n/a","sector":"Consumer Services","stock":"Arbor Realty Trust","symbol":"ABRN","industry":"Real Estate Investment Trusts"},
{"id":305,"market_cap":"$1.9B","sector":"Energy","stock":"Frank&#39;s International N.V.","symbol":"FI","industry":"Oilfield Services/Equipment"},
{"id":306,"market_cap":"$135.82M","sector":"Health Care","stock":"OncoMed Pharmaceuticals, Inc.","symbol":"OMED","industry":"Major Pharmaceuticals"},
{"id":307,"market_cap":"$80.04M","sector":"Technology","stock":"Great Elm Capital Group, Inc. ","symbol":"GEC","industry":"Computer Software: Prepackaged Software"},
{"id":308,"market_cap":"$380.3M","sector":"n/a","stock":"iShares Morningstar Mid-Cap ETF","symbol":"JKI","industry":"n/a"},
{"id":309,"market_cap":"$580.22M","sector":"Finance","stock":"Citigroup Inc.","symbol":"BLW","industry":"Major Banks"},
{"id":310,"market_cap":"$1.05B","sector":"Health Care","stock":"The Ensign Group, Inc.","symbol":"ENSG","industry":"Hospital/Nursing Management"},
{"id":311,"market_cap":"$5.24M","sector":"Consumer Non-Durables","stock":"Leading Brands Inc","symbol":"LBIX","industry":"Beverages (Production/Distribution)"},
{"id":312,"market_cap":"$4.88B","sector":"Capital Goods","stock":"Colfax Corporation","symbol":"CFX","industry":"Fluid Controls"},
{"id":313,"market_cap":"n/a","sector":"n/a","stock":"BlueStar TA-BIGITech Israel Technology ETF","symbol":"ITEQ","industry":"n/a"},
{"id":314,"market_cap":"$1.26B","sector":"Consumer Services","stock":"Agree Realty Corporation","symbol":"ADC","industry":"Real Estate Investment Trusts"},
{"id":315,"market_cap":"n/a","sector":"Finance","stock":"Vantage Energy Acquisition Corp.","symbol":"VEACU","industry":"Business Services"},
{"id":316,"market_cap":"$1.73B","sector":"Transportation","stock":"Heartland Express, Inc.","symbol":"HTLD","industry":"Trucking Freight/Courier Services"},
{"id":317,"market_cap":"n/a","sector":"n/a","stock":"AmTrust Financial Services, Inc.","symbol":"AFSI^D","industry":"n/a"},
{"id":318,"market_cap":"$146.32M","sector":"Health Care","stock":"Conatus Pharmaceuticals Inc.","symbol":"CNAT","industry":"Major Pharmaceuticals"},
{"id":319,"market_cap":"$2.09B","sector":"Technology","stock":"MicroStrategy Incorporated","symbol":"MSTR","industry":"Computer Software: Prepackaged Software"},
{"id":320,"market_cap":"$225.24M","sector":"Finance","stock":"VelocityShares 3x Long Silver ETN","symbol":"USLV","industry":"Investment Bankers/Brokers/Service"},
{"id":321,"market_cap":"$56.73M","sector":"Health Care","stock":"Concordia International Corp.","symbol":"CXRX","industry":"Major Pharmaceuticals"},
{"id":322,"market_cap":"$433.94M","sector":"n/a","stock":"First Trust Europe AlphaDEX Fund","symbol":"FEP","industry":"n/a"},
{"id":323,"market_cap":"n/a","sector":"Finance","stock":"Civista Bancshares, Inc. ","symbol":"CIVBP","industry":"Major Banks"},
{"id":324,"market_cap":"n/a","sector":"n/a","stock":"Legg Mason Emerging Markets Diversified Core ETF","symbol":"EDBI","industry":"n/a"},
{"id":325,"market_cap":"$13.88B","sector":"Consumer Services","stock":"Liberty Media Corporation","symbol":"LSXMK","industry":"Broadcasting"},
{"id":326,"market_cap":"$195.96M","sector":"Technology","stock":"Graham Corporation","symbol":"GHM","industry":"Industrial Machinery/Components"},
{"id":327,"market_cap":"$327.09M","sector":"n/a","stock":"Western Asset/Claymore U.S. Treasury Inflation Prot Secs Fd","symbol":"WIA","industry":"n/a"},
{"id":328,"market_cap":"n/a","sector":"n/a","stock":"Global X Conscious Companies ETF","symbol":"KRMA","industry":"n/a"},
{"id":329,"market_cap":"$49.09M","sector":"Finance","stock":"Unico American Corporation","symbol":"UNAM","industry":"Property-Casualty Insurers"},
{"id":330,"market_cap":"$40.95M","sector":"n/a","stock":"First Trust Emerging Markets Local Currency Bond ETF","symbol":"FEMB","industry":"n/a"},
{"id":331,"market_cap":"$18.33M","sector":"Health Care","stock":"Cyclacel Pharmaceuticals, Inc.","symbol":"CYCC","industry":"Major Pharmaceuticals"},
{"id":332,"market_cap":"$24.27B","sector":"Public Utilities","stock":"Xcel Energy Inc.","symbol":"XEL","industry":"Power Generation"},
{"id":333,"market_cap":"$3.1B","sector":"Finance","stock":"Cathay General Bancorp","symbol":"CATY","industry":"Major Banks"},
{"id":334,"market_cap":"$201.19M","sector":"Finance","stock":"SmartFinancial, Inc.","symbol":"SMBK","industry":"Major Banks"},
{"id":335,"market_cap":"n/a","sector":"n/a","stock":"FIRST REPUBLIC BANK","symbol":"FRC^F","industry":"n/a"},
{"id":336,"market_cap":"$157.67M","sector":"Finance","stock":"Griffin Industrial Realty, Inc.","symbol":"GRIF","industry":"Real Estate"},
{"id":337,"market_cap":"$6.95B","sector":"n/a","stock":"Ares Capital Corporation","symbol":"ARCC","industry":"n/a"},
{"id":338,"market_cap":"n/a","sector":"Finance","stock":"SB Financial Group, Inc.","symbol":"SBFGP","industry":"Major Banks"},
{"id":339,"market_cap":"$22.49B","sector":"Public Utilities","stock":"Public Service Enterprise Group Incorporated","symbol":"PEG","industry":"Power Generation"},
{"id":340,"market_cap":"$264.56M","sector":"Finance","stock":"Tiptree Inc.","symbol":"TIPT","industry":"Property-Casualty Insurers"},
{"id":341,"market_cap":"$463.09M","sector":"Consumer Services","stock":"Hibbett Sports, Inc.","symbol":"HIBB","industry":"Other Specialty Stores"},
{"id":342,"market_cap":"$12.81M","sector":"Finance","stock":"VelocityShares VIX Short-Term ETN","symbol":"VIIX","industry":"Investment Bankers/Brokers/Service"},
{"id":343,"market_cap":"$4.42B","sector":"Technology","stock":"Medidata Solutions, Inc.","symbol":"MDSO","industry":"Computer Software: Prepackaged Software"},
{"id":344,"market_cap":"$1.72B","sector":"Consumer Services","stock":"Builders FirstSource, Inc.","symbol":"BLDR","industry":"RETAIL: Building Materials"},
{"id":345,"market_cap":"$558.63M","sector":"Capital Goods","stock":"Babcock","symbol":"BW","industry":"Building Products"},
{"id":346,"market_cap":"$112.2M","sector":"Energy","stock":"Chesapeake Granite Wash Trust","symbol":"CHKR","industry":"Oil & Gas Production"},
{"id":347,"market_cap":"$1.6B","sector":"Basic Industries","stock":"Innospec Inc.","symbol":"IOSP","industry":"Major Chemicals"},
{"id":348,"market_cap":"$694.28M","sector":"Basic Industries","stock":"Aegion Corp","symbol":"AEGN","industry":"Water Supply"},
{"id":349,"market_cap":"n/a","sector":"n/a","stock":"Special Opportunities Fund Inc.","symbol":"SPE^B","industry":"n/a"},
{"id":350,"market_cap":"n/a","sector":"n/a","stock":"Costamare Inc.","symbol":"CMRE^B","industry":"n/a"},
{"id":351,"market_cap":"$150.62M","sector":"Health Care","stock":"Sorrento Therapeutics, Inc.","symbol":"SRNE","industry":"Biotechnology: Commercial Physical & Biological Resarch"},
{"id":352,"market_cap":"$23.64B","sector":"Capital Goods","stock":"Ingersoll-Rand plc (Ireland)","symbol":"IR","industry":"Auto Parts:O.E.M."},
{"id":353,"market_cap":"n/a","sector":"n/a","stock":"NRG Yield, Inc.","symbol":"NYLD.A","industry":"n/a"},
{"id":354,"market_cap":"$210.14M","sector":"n/a","stock":"RiverNorth/DoubleLine Strategic Opportunity Fund, Inc.","symbol":"OPP","industry":"n/a"},
{"id":355,"market_cap":"$2.25B","sector":"Finance","stock":"AllianceBernstein Holding L.P.","symbol":"AB","industry":"Investment Managers"},
{"id":356,"market_cap":"$333.23M","sector":"n/a","stock":"Vanguard Russell 3000 ETF","symbol":"VTHR","industry":"n/a"},
{"id":357,"market_cap":"$16.06B","sector":"Technology","stock":"Xilinx, Inc.","symbol":"XLNX","industry":"Semiconductors"},
{"id":358,"market_cap":"$4.23B","sector":"Finance","stock":"Investors Bancorp, Inc.","symbol":"ISBC","industry":"Major Banks"},
{"id":359,"market_cap":"$4.23B","sector":"Technology","stock":"j2 Global, Inc.","symbol":"JCOM","industry":"Telecommunications Equipment"},
{"id":360,"market_cap":"$1.59B","sector":"Capital Goods","stock":"Orbotech Ltd.","symbol":"ORBK","industry":"Industrial Machinery/Components"},
{"id":361,"market_cap":"n/a","sector":"Finance","stock":"Navient Corporation","symbol":"JSM","industry":"Finance: Consumer Services"},
{"id":362,"market_cap":"$2.69B","sector":"Consumer Services","stock":"First Cash, Inc.","symbol":"FCFS","industry":"Other Specialty Stores"},
{"id":363,"market_cap":"$1.15B","sector":"Health Care","stock":"Acceleron Pharma Inc.","symbol":"XLRN","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":364,"market_cap":"$321.59M","sector":"Finance","stock":"Marlin Business Services Corp.","symbol":"MRLN","industry":"Major Banks"},
{"id":365,"market_cap":"$12.63M","sector":"Capital Goods","stock":"Bonso Electronics International, Inc.","symbol":"BNSO","industry":"Industrial Machinery/Components"},
{"id":366,"market_cap":"$86.58M","sector":"n/a","stock":"Blackrock Enhanced Government Fund, Inc","symbol":"EGF","industry":"n/a"},
{"id":367,"market_cap":"$1.96B","sector":"Finance","stock":"ServisFirst Bancshares, Inc.","symbol":"SFBS","industry":"Major Banks"},
{"id":368,"market_cap":"$308.89M","sector":"Basic Industries","stock":"Ameresco, Inc.","symbol":"AMRC","industry":"Engineering & Construction"},
{"id":369,"market_cap":"$1.65B","sector":"Technology","stock":"Coupa Software Incorporated","symbol":"COUP","industry":"Computer Software: Prepackaged Software"},
{"id":370,"market_cap":"$29.24M","sector":"Technology","stock":"Qumu Corporation","symbol":"QUMU","industry":"Computer Software: Prepackaged Software"},
{"id":371,"market_cap":"$1.35B","sector":"Consumer Services","stock":"Time Inc.","symbol":"TIME","industry":"Newspapers/Magazines"},
{"id":372,"market_cap":"$255.79M","sector":"Technology","stock":"Immersion Corporation","symbol":"IMMR","industry":"Computer peripheral equipment"},
{"id":373,"market_cap":"n/a","sector":"n/a","stock":"Bank of America Corporation","symbol":"BAC.WS.A","industry":"n/a"},
{"id":374,"market_cap":"$1.68B","sector":"Energy","stock":"Semgroup Corporation","symbol":"SEMG","industry":"Oilfield Services/Equipment"},
{"id":375,"market_cap":"$2.73B","sector":"Health Care","stock":"Wright Medical Group N.V.","symbol":"WMGI","industry":"Industrial Specialties"},
{"id":376,"market_cap":"$664.15M","sector":"Health Care","stock":"Anika Therapeutics Inc.","symbol":"ANIK","industry":"Medical/Dental Instruments"},
{"id":377,"market_cap":"$985.94M","sector":"n/a","stock":"TCP Capital Corp.","symbol":"TCPC","industry":"n/a"},
{"id":378,"market_cap":"$78.51B","sector":"Health Care","stock":"CVS Health Corporation","symbol":"CVS","industry":"Medical/Nursing Services"},
{"id":379,"market_cap":"$673.15M","sector":"Health Care","stock":"Editas Medicine, Inc.","symbol":"EDIT","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":380,"market_cap":"$51.2M","sector":"Consumer Non-Durables","stock":"LRAD Corporation","symbol":"LRAD","industry":"Consumer Electronics/Appliances"},
{"id":381,"market_cap":"$165.71M","sector":"n/a","stock":"Colonial High Income Municipal Trust","symbol":"CXE","industry":"n/a"},
{"id":382,"market_cap":"n/a","sector":"n/a","stock":"Davis Select Worldwide ETF","symbol":"DWLD","industry":"n/a"},
{"id":383,"market_cap":"$896.52M","sector":"Capital Goods","stock":"MTS Systems Corporation","symbol":"MTSC","industry":"Industrial Machinery/Components"},
{"id":384,"market_cap":"$1.29B","sector":"Capital Goods","stock":"Mobile Mini, Inc.","symbol":"MINI","industry":"Metal Fabrications"},
{"id":385,"market_cap":"$177.71M","sector":"Finance","stock":"First Internet Bancorp","symbol":"INBK","industry":"Major Banks"},
{"id":386,"market_cap":"$267.73M","sector":"Energy","stock":"Lilis Energy, Inc.","symbol":"LLEX","industry":"Oil & Gas Production"},
{"id":387,"market_cap":"$68.96M","sector":"Energy","stock":"Sundance Energy Australia Limited","symbol":"SNDE","industry":"Oil & Gas Production"},
{"id":388,"market_cap":"$12.31M","sector":"Energy","stock":"American Electric Technologies, Inc.","symbol":"AETI","industry":"Industrial Machinery/Components"},
{"id":389,"market_cap":"$42.55M","sector":"n/a","stock":"Asia Tigers Fund, Inc. (The)","symbol":"GRR","industry":"n/a"},
{"id":390,"market_cap":"$5.34B","sector":"Consumer Durables","stock":"Watsco, Inc.","symbol":"WSO","industry":"Industrial Machinery/Components"},
{"id":391,"market_cap":"$582.59M","sector":"Energy","stock":"Penn Virginia Corporation","symbol":"PVAC","industry":"Oil & Gas Production"},
{"id":392,"market_cap":"$883.27M","sector":"Capital Goods","stock":"Astronics Corporation","symbol":"ATRO","industry":"Military/Government/Technical"},
{"id":393,"market_cap":"$2.19B","sector":"Consumer Non-Durables","stock":"Coca-Cola Bottling Co. Consolidated","symbol":"COKE","industry":"Beverages (Production/Distribution)"},
{"id":394,"market_cap":"$70.79M","sector":"Finance","stock":"First US Bancshares, Inc.","symbol":"FUSB","industry":"Major Banks"},
{"id":395,"market_cap":"$121.6M","sector":"n/a","stock":"Great Elm Capital Corp.","symbol":"GECC","industry":"n/a"},
{"id":396,"market_cap":"$256.07M","sector":"n/a","stock":"BlackRock Investment Quality Municipal Trust Inc. (The)","symbol":"BKN","industry":"n/a"},
{"id":397,"market_cap":"$14.46B","sector":"Basic Industries","stock":"Martin Marietta Materials, Inc.","symbol":"MLM","industry":"Mining & Quarrying of Nonmetallic Minerals (No Fuels)"},
{"id":398,"market_cap":"$20.42B","sector":"Public Utilities","stock":"TELUS Corporation","symbol":"TU","industry":"Telecommunications Equipment"},
{"id":399,"market_cap":"$534.71M","sector":"n/a","stock":"Eaton Vance Enhance Equity Income Fund","symbol":"EOI","industry":"n/a"},
{"id":400,"market_cap":"$153.96M","sector":"Finance","stock":"Entegra Financial Corp.","symbol":"ENFC","industry":"Banks"},
{"id":401,"market_cap":"$1.6B","sector":"Basic Industries","stock":"Innospec Inc.","symbol":"IOSP","industry":"Major Chemicals"},
{"id":402,"market_cap":"$3.27B","sector":"Capital Goods","stock":"Kennametal Inc.","symbol":"KMT","industry":"Industrial Machinery/Components"},
{"id":403,"market_cap":"$1.73B","sector":"Technology","stock":"Ebix, Inc.","symbol":"EBIX","industry":"EDP Services"},
{"id":404,"market_cap":"$20.13M","sector":"Health Care","stock":"Proteon Therapeutics, Inc.","symbol":"PRTO","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":405,"market_cap":"$16.58B","sector":"Consumer Services","stock":"Dollar Tree, Inc.","symbol":"DLTR","industry":"Department/Specialty Retail Stores"},
{"id":406,"market_cap":"$97.38M","sector":"Finance","stock":"VelocityShares 3x Long Gold ETN","symbol":"UGLD","industry":"Investment Bankers/Brokers/Service"},
{"id":407,"market_cap":"$218.35M","sector":"n/a","stock":"Brasilagro Cia Brasileira De Propriedades Agricolas","symbol":"LND","industry":"n/a"},
{"id":408,"market_cap":"$150.22M","sector":"Consumer Durables","stock":"MediWound Ltd.","symbol":"MDWD","industry":"Specialty Chemicals"},
{"id":409,"market_cap":"n/a","sector":"n/a","stock":"Davis Select U.S. Equity ETF","symbol":"DUSA","industry":"n/a"},
{"id":410,"market_cap":"$2.49B","sector":"Consumer Services","stock":"Tanger Factory Outlet Centers, Inc.","symbol":"SKT","industry":"Real Estate Investment Trusts"},
{"id":411,"market_cap":"$59.69M","sector":"Miscellaneous","stock":"GRAVITY Co., Ltd.","symbol":"GRVY","industry":"Business Services"},
{"id":412,"market_cap":"$5.64B","sector":"Public Utilities","stock":"EQT Midstream Partners, LP","symbol":"EQM","industry":"Natural Gas Distribution"},
{"id":413,"market_cap":"$2.63M","sector":"Health Care","stock":"Rennova Health, Inc.","symbol":"RNVA","industry":"Precision Instruments"},
{"id":414,"market_cap":"$3.61B","sector":"n/a","stock":"Nuveen AMT-Free Quality Municipal Income Fund","symbol":"NEA","industry":"n/a"},
{"id":415,"market_cap":"$1.53B","sector":"Consumer Services","stock":"Suburban Propane Partners, L.P.","symbol":"SPH","industry":"Other Specialty Stores"},
{"id":416,"market_cap":"$1.93B","sector":"Miscellaneous","stock":"Verifone Systems, Inc.","symbol":"PAY","industry":"Office Equipment/Supplies/Services"},
{"id":417,"market_cap":"$255.79M","sector":"Technology","stock":"Immersion Corporation","symbol":"IMMR","industry":"Computer peripheral equipment"},
{"id":418,"market_cap":"$12.99M","sector":"n/a","stock":"WisdomTree Barclays Negative Duration U.S. Aggregate Bond Fund","symbol":"AGND","industry":"n/a"},
{"id":419,"market_cap":"$790.66M","sector":"n/a","stock":"Voya Prime Rate Trust","symbol":"PPR","industry":"n/a"},
{"id":420,"market_cap":"$4.64B","sector":"Finance","stock":"Credit Acceptance Corporation","symbol":"CACC","industry":"Finance: Consumer Services"},
{"id":421,"market_cap":"$1.62B","sector":"Capital Goods","stock":"Meritage Corporation","symbol":"MTH","industry":"Homebuilding"},
{"id":422,"market_cap":"$828.02M","sector":"Public Utilities","stock":"Partner Communications Company Ltd.","symbol":"PTNR","industry":"Telecommunications Equipment"},
{"id":423,"market_cap":"$1.63B","sector":"Finance","stock":"Terreno Realty Corporation","symbol":"TRNO","industry":"Real Estate"},
{"id":424,"market_cap":"$1.32B","sector":"Transportation","stock":"Atlas Air Worldwide Holdings","symbol":"AAWW","industry":"Transportation Services"},
{"id":425,"market_cap":"$1.64B","sector":"Finance","stock":"NBT Bancorp Inc.","symbol":"NBTB","industry":"Major Banks"},
{"id":426,"market_cap":"$33.71M","sector":"Technology","stock":"GigaMedia Limited","symbol":"GIGM","industry":"Computer Software: Programming, Data Processing"},
{"id":427,"market_cap":"$1.9B","sector":"Health Care","stock":"Halozyme Therapeutics, Inc.","symbol":"HALO","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":428,"market_cap":"$258.6M","sector":"n/a","stock":"LMP Capital and Income Fund Inc.","symbol":"SCD","industry":"n/a"},
{"id":429,"market_cap":"$689.02M","sector":"Capital Goods","stock":"Douglas Dynamics, Inc.","symbol":"PLOW","industry":"Construction/Ag Equipment/Trucks"},
{"id":430,"market_cap":"$24M","sector":"Consumer Non-Durables","stock":"Differential Brands Group Inc.","symbol":"DFBG","industry":"Apparel"},
{"id":431,"market_cap":"$104.02M","sector":"Health Care","stock":"IRIDEX Corporation","symbol":"IRIX","industry":"Biotechnology: Electromedical & Electrotherapeutic Apparatus"},
{"id":432,"market_cap":"$13.79M","sector":"Health Care","stock":"Apricus Biosciences, Inc.","symbol":"APRI","industry":"Major Pharmaceuticals"},
{"id":433,"market_cap":"$12.63M","sector":"Capital Goods","stock":"Bonso Electronics International, Inc.","symbol":"BNSO","industry":"Industrial Machinery/Components"},
{"id":434,"market_cap":"$535.68M","sector":"Finance","stock":"Fifth Third Bancorp","symbol":"FITBI","industry":"Major Banks"},
{"id":435,"market_cap":"$231.47M","sector":"Basic Industries","stock":"Matrix Service Company","symbol":"MTRX","industry":"Engineering & Construction"},
{"id":436,"market_cap":"$150.22M","sector":"Consumer Durables","stock":"MediWound Ltd.","symbol":"MDWD","industry":"Specialty Chemicals"},
{"id":437,"market_cap":"$1.09B","sector":"Public Utilities","stock":"Consolidated Communications Holdings, Inc.","symbol":"CNSL","industry":"Telecommunications Equipment"},
{"id":438,"market_cap":"$725.83M","sector":"Finance","stock":"Yintech Investment Holdings Limited","symbol":"YIN","industry":"Investment Bankers/Brokers/Service"},
{"id":439,"market_cap":"$75.19B","sector":"Finance","stock":"HDFC Bank Limited","symbol":"HDB","industry":"Commercial Banks"},
{"id":440,"market_cap":"$9.38B","sector":"Technology","stock":"VeriSign, Inc.","symbol":"VRSN","industry":"EDP Services"},
{"id":441,"market_cap":"$529.78M","sector":"n/a","stock":"Blackrock MuniAssets Fund, Inc.","symbol":"MUA","industry":"n/a"},
{"id":442,"market_cap":"n/a","sector":"n/a","stock":"Gabelli Dividend","symbol":"GDV^D","industry":"n/a"},
{"id":443,"market_cap":"$160.52M","sector":"n/a","stock":"Western Asset Municipal High Income Fund, Inc.","symbol":"MHF","industry":"n/a"},
{"id":444,"market_cap":"$2.55B","sector":"Finance","stock":"South State Corporation","symbol":"SSB","industry":"Major Banks"},
{"id":445,"market_cap":"$53.85M","sector":"Finance","stock":"Jacksonville Bancorp Inc.","symbol":"JXSB","industry":"Savings Institutions"},
{"id":446,"market_cap":"$628.13M","sector":"Finance","stock":"Double Eagle Acquisition Corp.","symbol":"EAGL","industry":"Business Services"},
{"id":447,"market_cap":"$208.46M","sector":"Health Care","stock":"Stemline Therapeutics, Inc.","symbol":"STML","industry":"Major Pharmaceuticals"},
{"id":448,"market_cap":"$99.51M","sector":"Energy","stock":"Zion Oil & Gas Inc","symbol":"ZN","industry":"Oil & Gas Production"},
{"id":449,"market_cap":"$82.39M","sector":"Consumer Services","stock":"Stein Mart, Inc.","symbol":"SMRT","industry":"Clothing/Shoe/Accessory Stores"},
{"id":450,"market_cap":"$317.23M","sector":"Miscellaneous","stock":"ServiceSource International, Inc.","symbol":"SREV","industry":"Business Services"},
{"id":451,"market_cap":"$48.64M","sector":"Capital Goods","stock":"Hebron Technology Co., Ltd.","symbol":"HEBT","industry":"Metal Fabrications"},
{"id":452,"market_cap":"$9.26B","sector":"Capital Goods","stock":"Trimble Inc.","symbol":"TRMB","industry":"Industrial Machinery/Components"},
{"id":453,"market_cap":"n/a","sector":"Finance","stock":"Landcadia Holdings, Inc.","symbol":"LCAHU","industry":"Business Services"},
{"id":454,"market_cap":"n/a","sector":"Health Care","stock":"Rennova Health, Inc.","symbol":"RNVAZ","industry":"Precision Instruments"},
{"id":455,"market_cap":"$1.9B","sector":"Consumer Durables","stock":"Cooper Tire & Rubber Company","symbol":"CTB","industry":"Automotive Aftermarket"},
{"id":456,"market_cap":"n/a","sector":"n/a","stock":"Aspen Insurance Holdings Limited","symbol":"AHL^C","industry":"n/a"},
{"id":457,"market_cap":"$754.28M","sector":"Health Care","stock":"Esperion Therapeutics, Inc.","symbol":"ESPR","industry":"Major Pharmaceuticals"},
{"id":458,"market_cap":"$587.96M","sector":"Finance","stock":"First Financial Corporation Indiana","symbol":"THFF","industry":"Major Banks"},
{"id":459,"market_cap":"$222.61M","sector":"Energy","stock":"Seadrill Limited","symbol":"SDRL","industry":"Oil & Gas Production"},
{"id":460,"market_cap":"$33.43M","sector":"Consumer Durables","stock":"Jason Industries, Inc.","symbol":"JASN","industry":"Miscellaneous manufacturing industries"},
{"id":461,"market_cap":"$40.47B","sector":"Public Utilities","stock":"BCE, Inc.","symbol":"BCE","industry":"Telecommunications Equipment"},
{"id":462,"market_cap":"$3B","sector":"Energy","stock":"PDC Energy, Inc.","symbol":"PDCE","industry":"Oil & Gas Production"},
{"id":463,"market_cap":"$94.05M","sector":"n/a","stock":"Managed Duration Investment Grade Municipal Fund","symbol":"MZF","industry":"n/a"},
{"id":464,"market_cap":"$37M","sector":"Finance","stock":"National Security Group, Inc.","symbol":"NSEC","industry":"Life Insurance"},
{"id":465,"market_cap":"$1.53B","sector":"Finance","stock":"Union Bankshares Corporation","symbol":"UBSH","industry":"Major Banks"},
{"id":466,"market_cap":"$323.02M","sector":"n/a","stock":"Royce Micro-Cap Trust, Inc.","symbol":"RMT","industry":"n/a"},
{"id":467,"market_cap":"$739.26M","sector":"Technology","stock":"Rapid7, Inc.","symbol":"RPD","industry":"Computer Software: Prepackaged Software"},
{"id":468,"market_cap":"$65.53M","sector":"Miscellaneous","stock":"FuelCell Energy, Inc.","symbol":"FCEL","industry":"Industrial Machinery/Components"},
{"id":469,"market_cap":"$52.66M","sector":"n/a","stock":"First Trust RiverFront Dynamic Europe ETF","symbol":"RFEU","industry":"n/a"},
{"id":470,"market_cap":"$13.07B","sector":"Public Utilities","stock":"Ultrapar Participacoes S.A.","symbol":"UGP","industry":"Oil/Gas Transmission"},
{"id":471,"market_cap":"$286.77M","sector":"Basic Industries","stock":"Sterling Construction Company Inc","symbol":"STRL","industry":"Military/Government/Technical"},
{"id":472,"market_cap":"$611.82M","sector":"Consumer Services","stock":"Nordic American Tankers Limited","symbol":"NAT","industry":"Marine Transportation"},
{"id":473,"market_cap":"$664.71M","sector":"Energy","stock":"TransMontaigne Partners L.P.","symbol":"TLP","industry":"Natural Gas Distribution"},
{"id":474,"market_cap":"$7.15B","sector":"Basic Industries","stock":"Aluminum Corporation of China Limited","symbol":"ACH","industry":"Aluminum"},
{"id":475,"market_cap":"$44.38M","sector":"Consumer Durables","stock":"China Jo-Jo Drugstores, Inc.","symbol":"CJJD","industry":"Specialty Chemicals"},
{"id":476,"market_cap":"n/a","sector":"Health Care","stock":"Onconova Therapeutics, Inc.","symbol":"ONTXW","industry":"Major Pharmaceuticals"},
{"id":477,"market_cap":"$5.25B","sector":"Consumer Non-Durables","stock":"Post Holdings, Inc.","symbol":"POST","industry":"Packaged Foods"},
{"id":478,"market_cap":"$122.37M","sector":"Transportation","stock":"StealthGas, Inc.","symbol":"GASS","industry":"Marine Transportation"},
{"id":479,"market_cap":"$467.31M","sector":"Finance","stock":"Everi Holdings Inc.","symbol":"EVRI","industry":"Finance: Consumer Services"},
{"id":480,"market_cap":"$3.61B","sector":"Technology","stock":"CoreLogic, Inc.","symbol":"CLGX","industry":"EDP Services"},
{"id":481,"market_cap":"$53.4B","sector":"Health Care","stock":"Biogen Inc.","symbol":"BIIB","industry":"Biotechnology: Biological Products (No Diagnostic Substances)"},
{"id":482,"market_cap":"$151.22M","sector":"Technology","stock":"Perion Network Ltd","symbol":"PERI","industry":"EDP Services"},
{"id":483,"market_cap":"$94.83M","sector":"n/a","stock":"PowerShares DWA Energy Momentum Portfolio","symbol":"PXI","industry":"n/a"},
{"id":484,"market_cap":"$5.21B","sector":"Capital Goods","stock":"Gentex Corporation","symbol":"GNTX","industry":"Auto Parts:O.E.M."},
{"id":485,"market_cap":"$55.33M","sector":"Transportation","stock":"USA Truck, Inc.","symbol":"USAK","industry":"Trucking Freight/Courier Services"},
{"id":486,"market_cap":"n/a","sector":"n/a","stock":"Ashford Hospitality Trust Inc","symbol":"AHT^F","industry":"n/a"},
{"id":487,"market_cap":"$66.96M","sector":"Consumer Services","stock":"Stage Stores, Inc.","symbol":"SSI","industry":"Clothing/Shoe/Accessory Stores"},
{"id":488,"market_cap":"$30.09B","sector":"Capital Goods","stock":"CRH PLC","symbol":"CRH","industry":"Building Materials"},
{"id":489,"market_cap":"$345.19M","sector":"Consumer Services","stock":"Community Healthcare Trust Incorporated","symbol":"CHCT","industry":"Real Estate Investment Trusts"},
{"id":490,"market_cap":"n/a","sector":"n/a","stock":"Endurance Specialty Holdings Ltd","symbol":"ENH^C","industry":"n/a"},
{"id":491,"market_cap":"$1.05B","sector":"Finance","stock":"Infinity Property and Casualty Corporation","symbol":"IPCC","industry":"Property-Casualty Insurers"},
{"id":492,"market_cap":"$298.04M","sector":"Consumer Services","stock":"Potbelly Corporation","symbol":"PBPB","industry":"Restaurants"},
{"id":493,"market_cap":"$1.53B","sector":"Consumer Services","stock":"Four Corners Property Trust, Inc.","symbol":"FCPT","industry":"Real Estate Investment Trusts"},
{"id":494,"market_cap":"$86.31M","sector":"Transportation","stock":"Celadon Group, Inc.","symbol":"CGI","industry":"Trucking Freight/Courier Services"},
{"id":495,"market_cap":"$475.98M","sector":"Finance","stock":"Cowen Inc.","symbol":"COWN","industry":"Investment Bankers/Brokers/Service"},
{"id":496,"market_cap":"$3.27B","sector":"Capital Goods","stock":"Kennametal Inc.","symbol":"KMT","industry":"Industrial Machinery/Components"},
{"id":497,"market_cap":"$71.34M","sector":"n/a","stock":"Gabelli Convertible and Income Securities Fund, Inc. (The)","symbol":"GCV","industry":"n/a"},
{"id":498,"market_cap":"$1.26B","sector":"Capital Goods","stock":"Wabash National Corporation","symbol":"WNC","industry":"Construction/Ag Equipment/Trucks"},
{"id":499,"market_cap":"n/a","sector":"n/a","stock":"Costamare Inc.","symbol":"CMRE^C","industry":"n/a"},
{"id":500,"market_cap":"$184.08M","sector":"Basic Industries","stock":"Olympic Steel, Inc.","symbol":"ZEUS","industry":"Metal Fabrications"}]

// Helpers
// Convert string to float number
let toInteger = R.pipe(
  d => d.replace(/[^0-9.]/g, ''),
  parseFloat
)
// Calc average
let average = (arr) => arr.reduce((sum, tally) => sum + tally, 0) / arr.length

// Add market_cap_int property
let addMarketCapInt = (arr) => arr.map(o => Object.assign({}, o, {market_cap_int: toInteger(o.market_cap)}))

// ======== Basic data filtering and manipulation for big health stocks

// Filter for big health stocks
let filterHealthBigCap = R.filter(R.where({
  sector: R.equals('Health Care'),
  market_cap: o => toInteger(o) > 100
}))

let x = filterHealthBigCap(data)
x

// List all big health stocks by market_cap descending
let healthSort = R.pipe(
  filterHealthBigCap,
  addMarketCapInt,
  R.sortWith([R.descend(R.prop('market_cap_int'))])
)

let sorted = healthSort(data)

// Avg marketcap of big health stocks
let healthAvgMktCap = R.pipe(
  filterHealthBigCap,
  R.map(o => toInteger(o.market_cap)),
  average
)

let result = healthAvgMktCap(data) // 371